from django import forms

EFFORT_CHOICES = (('dynamic', 'Dynamic'), ('max', 'Max'))
BOXFREE_CHOICES = (('free', 'Free'), ('box', 'Box'))
SUMO_CHOICES = (('sumo', 'Sumo'), ('conventional', 'Conventional'))

class SquatForm(forms.Form):
	effort_type = forms.ChoiceField(widget=forms.RadioSelect, choices = EFFORT_CHOICES)
	box_free = forms.ChoiceField(widget=forms.RadioSelect, choices = BOXFREE_CHOICES)
	bar_type = forms.CharField(required = False, max_length=60)
	bands_type = forms.CharField(required = False, max_length=60)
	chain_weight = forms.IntegerField(required = False, initial = 0)
	movement_weight = forms.IntegerField(required = False, initial = 0)
	movement_reps = forms.IntegerField(required = False, initial = 0)

class DeadliftForm(forms.Form):
	sumo_conventional = forms.ChoiceField(widget=forms.RadioSelect, choices = SUMO_CHOICES)
	deficit = forms.BooleanField(required = False)
	block = forms.BooleanField(required = False)
	standard = forms.BooleanField(required = False)
	pin = forms.BooleanField(required = False)
	reverse = forms.BooleanField(required = False)
	movement_weight = forms.IntegerField(required = False, initial = 0)
	movement_reps = forms.IntegerField(required = False, initial = 0)
	deadlift_notes = forms.CharField(max_length=60,required = False)

class BenchForm(forms.Form):
	bar_type = forms.CharField(max_length=60)
	floor = forms.BooleanField()
	reverse = forms.BooleanField()
	standard = forms.BooleanField()
	board = forms.BooleanField()
	manpon = forms.BooleanField()
	pin = forms.BooleanField()
	notes = forms.CharField(max_length=60)
	bands = forms.CharField(max_length=60)
	chains = forms.CharField(max_length=60)

class UpperForm(forms.Form):
    top_set = forms.CharField(max_length=60)
    close_grippness = forms.CharField(max_length=60)
    tate_press = forms.CharField(max_length=60)
    dips = forms.CharField(max_length=60)
    rev_db_fly = forms.CharField(max_length=60)
    windmills = forms.CharField(max_length=60)
    bamboo_bar = forms.CharField(max_length=60)
    lat_pulldowns = forms.CharField(max_length=60)
    lat_pullovers = forms.CharField(max_length=60)
    pec_dec = forms.CharField(max_length=60)
    reverse_pec_dec = forms.CharField(max_length=60)
    t_bar_rows = forms.CharField(max_length=60)
    chest_supported_rows = forms.CharField(max_length=60)
    low_rows = forms.CharField(max_length=60)
    pullups = forms.CharField(max_length=60)
    inverted_row = forms.CharField(max_length=60)
    face_pulls = forms.CharField(max_length=60)
    db_rows = forms.CharField(max_length=60)
    db_press = forms.CharField(max_length=60)
    pullaparts = forms.CharField(max_length=60)
    tri_extensions = forms.CharField(max_length=60)
    skull_crushers = forms.CharField(max_length=60)
    jam_press = forms.CharField(max_length=60)
    olt_press = forms.CharField(max_length=60)
    db_rollbacks = forms.CharField(max_length=60)
    dead_press = forms.CharField(max_length=60)


class LowerForm(forms.Form):
    chair_dl = forms.CharField(max_length=60)
    ghr = forms.CharField(max_length=60)
    lunge = forms.CharField(max_length=60)
    dimel_dl = forms.CharField(max_length=60)
    reverse_hyper = forms.CharField(max_length=60)
    hip_bridge = forms.CharField(max_length=60)
    good_morning = forms.CharField(max_length=60)
    step_up = forms.CharField(max_length=60)
    belt_squat = forms.CharField(max_length=60)
    hack_squat = forms.CharField(max_length=60)
    leg_press = forms.CharField(max_length=60)
    leg_curl = forms.CharField(max_length=60)
    stiff_leg_dl = forms.CharField(max_length=60)
    inverse_curl = forms.CharField(max_length=60)
    front_squat = forms.CharField(max_length=60)
    back_extension = forms.CharField(max_length=60)
    top_set = forms.CharField(max_length=60)
