from django import forms

EFFORT_CHOICES = (('dynamic', 'Dynamic Effort'), ('max', 'Max Effort'))
BOXFREE_CHOICES = (('free', 'Free'), ('box', 'Box'))
SUMO_CHOICES = (('sumo', 'Sumo'), ('conventional', 'Conventional'))

class SquatForm(forms.Form):
	effort_type = forms.ChoiceField(label="Day", widget=forms.RadioSelect, choices=EFFORT_CHOICES)
	box_free = forms.ChoiceField(label="Squat Type", widget=forms.RadioSelect, choices=BOXFREE_CHOICES)
	bar_type = forms.CharField(required=False, max_length=60)
	bands_type = forms.CharField(label="Band Type", required=False, max_length=60)
	chain_weight = forms.IntegerField(required=False, initial=0)
	movement_weight = forms.IntegerField(label="Bar Weight", required=False, initial=0)
	movement_reps = forms.IntegerField(label="Reps",required=False, initial=0)
	squat_notes = forms.CharField(max_length=300,widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Add Squat Notes Here'}),required=False)

class DeadliftForm(forms.Form):
	sumo_conventional = forms.ChoiceField(label="Deadlift Style",widget=forms.RadioSelect, choices=SUMO_CHOICES)
	deficit = forms.BooleanField(required=False)
	block = forms.BooleanField(required=False)
	standard = forms.BooleanField(required=False)
	pin = forms.BooleanField(required=False)
	reverse = forms.BooleanField(label="Reverse Band",required=False)
	movement_weight = forms.IntegerField(label="Bar Weight",required=False, initial=0)
	movement_reps = forms.IntegerField(label="Reps",required=False, initial=0)
	deadlift_notes = forms.CharField(max_length=300,widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Add Deadlift Notes Here'}),required=False)

class BenchForm(forms.Form):
	bar_type = forms.CharField(max_length=60)
	floor = forms.BooleanField(label="Floor Press",required=False)
	reverse = forms.BooleanField(label="Reverse Band",required=False)
	standard = forms.BooleanField(label="Straight Weight",required=False)
	board = forms.BooleanField(required=False)
	manpon = forms.BooleanField(required=False)
	pin = forms.BooleanField(required=False)
	bands = forms.CharField(required=False,max_length=60)
	chains = forms.CharField(required=False,max_length=60)
	movement_weight = forms.IntegerField(label="Bar Weight",required=False, initial=0)
	movement_reps = forms.IntegerField(label="Reps",required=False, initial=0)
	bench_notes = forms.CharField(required=False,max_length=300,widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Add Bench Notes Here'}))


class UpperForm(forms.Form):
	top_set = forms.CharField(required=False,max_length=60)
	close_grippness = forms.CharField(label="Close Grip",required=False,max_length=60)
	tate_press = forms.CharField(required=False,max_length=60)
	dips = forms.CharField(required=False,max_length=60)
	rev_db_fly = forms.CharField(label="Rev DB Fly",required=False,max_length=60)
	windmills = forms.CharField(required=False,max_length=60)
	bamboo_bar = forms.CharField(required=False,max_length=60)
	lat_pulldowns = forms.CharField(required=False,max_length=60)
	lat_pullovers = forms.CharField(required=False,max_length=60)
	pec_dec = forms.CharField(required=False,max_length=60)
	reverse_pec_dec = forms.CharField(required=False,max_length=60)
	t_bar_rows = forms.CharField(required=False,max_length=60)
	chest_supported_rows = forms.CharField(required=False,max_length=60)
	low_rows = forms.CharField(required=False,max_length=60)
	pullups = forms.CharField(required=False,max_length=60)
	inverted_row = forms.CharField(required=False,max_length=60)
	face_pulls = forms.CharField(required=False,max_length=60)
	db_rows = forms.CharField(label="DB Rows",required=False,max_length=60)
	db_press = forms.CharField(label="DB Press",required=False,max_length=60)
	pullaparts = forms.CharField(required=False,max_length=60)
	tri_extensions = forms.CharField(required=False,max_length=60)
	skull_crushers = forms.CharField(required=False,max_length=60)
	jam_press = forms.CharField(label="JM Press",required=False,max_length=60)
	olt_press = forms.CharField(label="Overhead Press",required=False,max_length=60)
	db_rollbacks = forms.CharField(label="DB Rollbacks",required=False,max_length=60)
	dead_press = forms.CharField(required=False,max_length=60)
	ab_movement = forms.CharField(required=False,max_length=60)
	notes = forms.CharField(required=False,max_length=300,widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Add Upper Accessory Notes Here'}))


class LowerForm(forms.Form):
	top_set = forms.CharField(required=False,max_length=60)
	chair_dl = forms.CharField(label="Chair Deadlift",required=False,max_length=60)
	ghr = forms.CharField(label="GHR",required=False,max_length=60)
	lunge = forms.CharField(required=False,max_length=60)
	dimel_dl = forms.CharField(label="Dimel DL",required=False,max_length=60)
	reverse_hyper = forms.CharField(required=False,max_length=60)
	hip_bridge = forms.CharField(required=False,max_length=60)
	good_morning = forms.CharField(required=False,max_length=60)
	step_up = forms.CharField(required=False,max_length=60)
	belt_squat = forms.CharField(required=False,max_length=60)
	hack_squat = forms.CharField(required=False,max_length=60)
	leg_press = forms.CharField(required=False,max_length=60)
	leg_curl = forms.CharField(required=False,max_length=60)
	stiff_leg_dl = forms.CharField(label="Stiff Leg DL",required=False,max_length=60)
	inverse_curl = forms.CharField(required=False,max_length=60)
	front_squat = forms.CharField(required=False,max_length=60)
	back_extension = forms.CharField(required=False,max_length=60)
	ab_movement = forms.CharField(required=False,max_length=60)
	notes = forms.CharField(required=False,max_length=300,widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Add Lower Accessory Notes Here'}))
