# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('upper_lower', models.CharField(max_length=60)),
                ('dynamic_max', models.CharField(max_length=60)),
                ('bb_db', models.CharField(max_length=60)),
                ('bar_type', models.CharField(max_length=60)),
                ('acc_resistance', models.CharField(max_length=60)),
                ('box_free', models.CharField(max_length=60)),
            ],
        ),
    ]
