# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='bb_db',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='dynamic_max',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='upper_lower',
        ),
        migrations.AddField(
            model_name='workout',
            name='barbell_workout',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='workout',
            name='dumbbell_workout',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='workout',
            name='dynamic_effort',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='workout',
            name='lower_body',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='workout',
            name='max_effort',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='workout',
            name='upper_body',
            field=models.NullBooleanField(),
        ),
    ]
