# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20170407_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='loweraccessorymovement',
            name='notes',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='squatmovement',
            name='squat_notes',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='upperaccessorymovement',
            name='notes',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='deadliftmovement',
            name='deadlift_notes',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
