# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20170528_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benchmovement',
            old_name='notes',
            new_name='bench_notes',
        ),
    ]
