# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20170528_1633'),
        ('tracker', '0004_auto_20170528_1626'),
    ]

    operations = [
    ]
