# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_merge_20170605_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmovement',
            name='movement_reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='benchmovement',
            name='movement_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loweraccessorymovement',
            name='ab_movement',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='upperaccessorymovement',
            name='ab_movement',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
