# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20170607_2026'),
        ('tracker', '0006_merge_20170602_0807'),
    ]

    operations = [
    ]
