# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_merge_20170607_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squatmovement',
            name='squat_notes',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
