# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20170613_1942'),
        ('tracker', '0006_merge_20170602_0807'),
    ]

    operations = [
    ]
