# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_merge_20170613_2048'),
        ('tracker', '0008_merge_20170609_1538'),
    ]

    operations = [
    ]
