# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_merge_20170613_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadliftmovement',
            name='chain_weight',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='benchmovement',
            name='chains',
            field=models.IntegerField(blank=True),
        ),
    ]
