# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_auto_20170621_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benchmovement',
            old_name='bands',
            new_name='bands_type',
        ),
        migrations.AddField(
            model_name='deadliftmovement',
            name='bands_type',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
