# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_auto_20170624_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmovement',
            name='effort_type',
            field=models.CharField(default='Dynamic', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deadliftmovement',
            name='effort_type',
            field=models.CharField(default='Dynamic', max_length=60),
            preserve_default=False,
        ),
    ]
