# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_auto_20170624_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmovement',
            name='media_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='deadliftmovement',
            name='media_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='loweraccessorymovement',
            name='media_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='squatmovement',
            name='media_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='upperaccessorymovement',
            name='media_url',
            field=models.URLField(blank=True),
        ),
    ]
