# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_auto_20170709_1800'),
        ('tracker', '0016_auto_20170716_1945'),
    ]

    operations = [
    ]
