# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_loweraccessorymovement_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='upperaccessorymovement',
            name='other',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
