# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-16 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_upperaccessorymovement_other'),
        ('tracker', '0018_auto_20170806_1623'),
    ]

    operations = [
    ]
