# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-17 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_upperaccessorymovement_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmovement',
            name='movement_sets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deadliftmovement',
            name='movement_sets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='squatmovement',
            name='movement_sets',
            field=models.IntegerField(default=0),
        ),
    ]
