# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_merge_20170816_1517'),
        ('tracker', '0020_auto_20170816_1823'),
    ]

    operations = [
    ]
