# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_auto_20170817_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadliftmovement',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
