# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-26 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0027_squatmovement_reverse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmovement',
            name='board',
            field=models.IntegerField(default=0),
        ),
    ]
