# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-09 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_auto_20171108_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmovement',
            name='created_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='deadliftmovement',
            name='created_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loweraccessorymovement',
            name='created_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='upperaccessorymovement',
            name='created_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
