# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-28 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0030_auto_20171108_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmovement',
            name='board',
            field=models.IntegerField(blank=True),
        ),
    ]
