# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-04 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0032_auto_20180129_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squatmovement',
            name='created_at',
            field=models.DateField(blank=True),
        ),
    ]
